name: 'PnP PowerShell Sharing Settings as Code'
description: 'Define and enforce SharePoint Online sharing settings with GitHub Actions'
inputs:
  SHAREPOINT_ADMIN_URL:
    description: 'URL of the SharePoint Admin Site'
    required: true
  CLIENT_ID:
    description: 'Username of the admin'
    required: true
  CLIENT_SECRET:
    description: 'Password of the admin'
    required: true
  SharingCapability_Disabled_Sites:
    description: 'Disable sharing capability'
    required: false
    default: 'null'
  SharingCapability_ExternalUserSharingOnly_Sites:
    description: 'Enable sharing capability for external users only'
    required: false
    default: 'null'
  SharingCapability_ExternalUserAndGuestSharing_Sites:
    description: 'Enable sharing capability for external users and guests'
    required: false
    default: 'null'
  SharingCapability_ExistingExternalUserSharingOnly_Sites:
    description: 'Enable sharing capability for existing external users only'
    required: false
    default: 'null'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'download'  
  color: 'blue'