name: 'PnP PowerShell Sharing Settings as Code'
description: 'Define and enforce SharePoint Online sharing settings with GitHub Actions. If "ALLELSE" is used for any of the settings (but only for ONE), it will apply to all sites which were NOT specified in the other settings. If "null" is used for any of the settings, it will skip that setting.'
inputs:
  SHAREPOINT_ADMIN_URL:
    description: 'URL of the SharePoint Admin Site'
    required: true
  CLIENT_ID:
    description: 'Username of the admin'
    required: true
  CLIENT_SECRET:
    description: 'Password of the admin'
    required: true
  SHARINGCAPABILITY_DISABLED_SITES:
    description: 'Comma separated list of URLS where to disable sharing capability. Or "null" or "ALLELSE".'
    required: false
    default: 'null'
  SHARINGCAPABILITY_EXTERNALUSERSHARINGONLY_SITES:
    description: 'Comma separated list of URLS where to enable sharing capability for external users only. Or "null" or "ALLELSE".'
    required: false
    default: 'null'
  SHARINGCAPABILITY_EXTERNALUSERANDGUESTSHARING_SITES:
    description: 'Comma separated list of URLS where to enable sharing capability for both external users and guests. Or "null" or "ALLELSE".'
    required: false
    default: 'null'
  SHARINGCAPABILITY_EXISTINGEXTERNALUSERSHARINGONLY_SITES:
    description: 'Comma separated list of URLS where to enable sharing capability for existing external users only. Or "null" or "ALLELSE".'
    required: false
    default: 'null'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'briefcase'
  color: 'blue'